services:
  - type: static_site
    name: devtracker
    plan: free
    buildCommand: ""
    staticPublishPath: .
    branch: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
